### ISSUE TITLE
Incorrect original position

### ISSUE THREAD

**Issue by privatenumber** [jridgewell/trace-mapping#14]
I'm using an input where the source and "compiled" code are identical.

However, when using `originalPositionFor`, the original position is not the same as the queried position.

*Disclaimer: I don't know much about the accuracy of source maps. Excuse me if not a bug.*

**Source**

```ts
let a=()=>{};\n
```

**Compiled**
I'm compiling using esbuild: [REPL](https://hyrious.me/esbuild-repl/?version=0.14.51&mode=transform&input=let+a%3D%28%29%3D%3E%7B%7D%3B%0A&options=--sourcemap+--minify)

```ts
let a=()=>{};\n
```

**Source map**
Based on [this visualization](https://evanw.github.io/source-map-visualization/#MTQAbGV0IGE9KCk9Pnt9OwoxNDMAewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiPHN0ZGluPiJdLAogICJzb3VyY2VzQ29udGVudCI6IFsibGV0IGE9KCk9Pnt9O1xuIl0sCiAgIm1hcHBpbmdzIjogIkFBQUEsSUFBSSxFQUFFLElBQUksQ0FBQyIsCiAgIm5hbWVzIjogW10KfQo=), it seems like the source map is accurate
```json5
{
    version: 3,
    sources: [ 'file:///test.js' ],
    sourcesContent: [ 'let a=()=>{};\n' ],
    mappings: 'AAAA,IAAI,EAAE,IAAI,CAAC',
    names: [],
    sourceRoot: ''
}
```

**Expected**
```ts
originalPositionFor(new TraceMap(sourceMap), { line: 1, column: 6 })
// => { line: 1, column: 6 } (Working expectedly)
```

**Unexpected**
```ts
originalPositionFor(new TraceMap(sourceMap), { line: 1, column: 13 })
// => { line: 1, column: 11 } (Unexpected -- column should be 13)
```

**Reproduction**
https://stackblitz.com/edit/node-gitae3?file=index.mjs

**Context**
I'm using the sourcemap to identify where to make code transformations, so the precise location is necessary.

**Comment by privatenumber** [comment]
I'm starting to understand that source maps map to ranges to there's room for inaccuracy (and hence the bias option).

I don't think this is a bug so I'm closing.

**Comment by jridgewell** [comment]
Sourcemap segments represent text ranges. When you trace `{ line: 1, column: 6 }`, you're hitting the segment that starts at generated output column 6 and ends at output column 10 (all of the text representing `()=>` in the output). Each output character is _not_ represented with an individual segment and original location. So every char in `()=>` points to the same original location, which happens to be `{ line: 1, column: 6 }` (because you're not making any edits to the file). If you were to trace `{ line: 1, column: 7 }` (the `)` char), you'd still get back `{ line: 1, column: 6 }`.

When you're tracing `{ line: 1, column: 13 }`, you're actually hitting the segment that starts at output column 11 and continues infinitely on that line (because there's not another segment afterwards to tell us where the output column ends). So the return `{ line: 1, column: 11 }` is correct based on the sourcemap that's given.

If you want higher fidelity positions, then you have to generate more segments in the `mappings` field (and make the sourcemap much larger). Otherwise, it's not guaranteed that we'll be able to find the exact source position.

You could infer this information using the lower level `traceSegment` API (but note that this is not a guarantee of exact source position). Eg, `traceSegment(map, 0, 13)` (the equivalent of `originalPositionFor(map, { line: 1, column: 13 })` would return `[11, 0, 0, 11]`. The first item in the tuple means the output column 11, and there's a difference of 2 columns. So you could add 2 to the source column (the 4th item in the tuple).

**Comment by privatenumber** [comment]
Thank you @jridgewell ! Really appreciate the thorough response & guidance.

Your suggestion seemed to work for the minimal example above, but as you said, it quickly became inaccurate on larger inputs where the source and compiled are not the same.

Here is the code I used:
```ts
const inferPosition = (map, { line, column }) => {
	const segment = traceSegment(map, line - 1, column);
	const difference = column - segment[0];

	return {
		line: segment[2] + 1,
		column: segment[3] + difference + 1,
	};
};
```

BTW, if it's possible to determine the original position with more accuracy, why doesn't `originalPositionFor` do that? Would this inference technique ever be more off than `originalPositionFor`?
