### ISSUE TITLE
Feature request: `allGeneratedPositionsFor`

### ISSUE THREAD

**Issue by connor4312** [jridgewell/trace-mapping#18]
The `source-map` library has a function, `allGeneratedPositionsFor`, which gets all candidate positions for the given source locations. I couldn't see to find a similar function in this library.

**Comment by jridgewell** [comment]
I don't have time to implement this right now, but it should be simple to add. The core behavior is already implemented for `generatedPositionFor`. We'd need:

1. Change [traceSegmentInternal](https://github.com/jridgewell/trace-mapping/blob/0cef9743cc3c8338c7f1287c63dd6e6afb2013a1/src/trace-mapping.ts#L392-L406) to return an index instead of a segment.
2. Extract the [common parts](https://github.com/jridgewell/trace-mapping/blob/0cef9743cc3c8338c7f1287c63dd6e6afb2013a1/src/trace-mapping.ts#L242-L267) of generated segment finding into a helper
3. Slice from the segment index until we hit a non-matching segment.

**Comment by jridgewell** [comment]
Closed by https://github.com/jridgewell/trace-mapping/pull/19
